Query was executed successfully

[(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),(16),(17),(18),(19),(20),(21),(22),(23),(24),(25),(26),(27),(28),(29),(30)]

SCIDB QUERY : <update unbounded set a=99 where a is not null>
[An error expected at this place for the query "update unbounded set a=99 where a is not null". And it failed with error code = scidb::SCIDB_SE_STORAGE::SCIDB_LE_CHUNK_ALREADY_EXISTS..]

SCIDB QUERY : <scan(unbounded)>
[(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),(16),(17),(18),(19),(20),(21),(22),(23),(24),(25),(26),(27),(28),(29),(30)]

Query was executed successfully

